name: Build library

on: [push, pull_request]

jobs:
    build:
        name: Build On ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        
        steps:
            - uses: actions/checkout@v4

            - name: Install SDL2 (Linux)
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt update && sudo apt install libsdl2-dev

            - name: Install SDL2 (Windows)
              if: matrix.os == 'windows-latest'
              run: choco install sdl2

            - name: Install SDL2 (macOS)
              if: matrix.os == 'macos-latest'
              run: brew install sdl2

            - name: configure
              run: cmake -B build -DCMAKE_BUILD_TYPE=Release
            
            - name: build
              run: cmake --build build --config Release
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: AURA.CORE-${{ matrix.os }}
                path: |
                    build/*.dll
                    build/*.so
                    build/*.dylib